# The testing matrix **for simp-packer** only considers ruby/puppet versions
# supported by SIMP:
# ------------------------------------------------------------------------------
#  release    pup   ruby   eol
# SIMP 6.0    4.8   2.1.9  TBD***
# SIMP 6.2    4.10  2.1.9  TBD
#
# *** = Modules created for SIMP 6.2+ are not required to support Puppet < 4.10
---
language: ruby
cache: bundler
sudo: false
bundler_args: --without development system_tests --path .vendor
notifications:
  email: false

stages:
  - validation
  - 'Puppet (SIMP versions)'
  - name: deploy
    if: 'fork = false AND tag = true'

before_install:
  - rm -f Gemfile.lock
  - gem update --system

jobs:
  allow_failures:
    - name: 'Latest Puppet 5.x (allowed to fail)'

  include:
    - stage:  validation
      name:   Rubocop
      script: bundle exec rake test:rubocop

#    - stage: deploy
#      script:
#        - true
#      deploy:
#        - provider: releases
#          on:
#            tags: true
#            condition: '($SKIP_FORGE_PUBLISH != true)'
#          skip_cleanup: true
#          api_key:
#            secure: <INSERT KEY HERE>
