Vagrant.configure("2") do |c|
  c.ssh.insert_key = false
  c.vm.define 'puppetserver' do |v|
    v.vm.hostname = 'puppetserver'
    v.vm.box = 'simpci/server-6.2.0-Beta2.el7-CentOS-7.0.x86-64'
    v.vm.box_url = 'BEAKER_box__puppetserver'
    v.vm.box_check_update = 'true'
    v.vm.synced_folder '.', '/vagrant', disabled: true
    v.vm.network :private_network, ip: "192.168.103.7", :netmask => "255.255.255.0", :mac => "aabbcccc0007"
    v.vm.provider :virtualbox do |vb|
      vb.customize ['modifyvm', :id, '--memory', '4096', '--cpus', '1']
    end
  end
end
